---
abstract: 'a client for a Sentry server.'
author:
  - 'Fran Rodriguez <kio@cpan.org>'
build_requires:
  Test::Fatal: 0
  Test::JSON: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Sentry-Client
requires:
  Carp: 0
  Compress::Zlib: 0
  Data::UUID::MT: 0
  DateTime: 0
  Digest::HMAC_SHA1: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Sys::Hostname: 0
  Time::HiRes: 0
  strict: 0
  warnings: 0
version: 0.001
